PRAGMA foreign_keys = ON;

CREATE TABLE OWNER ( 
    OwnerID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    ,FirstName TEXT NOT NULL
    ,LastName TEXT NOT NULL
);

CREATE TABLE OWNER_PHONENO ( 
    OwnerID INTEGER NOT NULL
    ,PhoneNumber TEXT NOT NULL
    ,PRIMARY KEY (OwnerID, PhoneNumber)
    ,FOREIGN KEY (OwnerID) REFERENCES OWNER(OwnerID) ON DELETE CASCADE
);

CREATE TABLE PET ( 
    PetID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    ,OwnerID INTEGER NOT NULL
    ,Name TEXT NOT NULL
    ,Weight_lbs REAL NOT NULL CHECK (Weight_lbs > 0)
    ,FOREIGN KEY (OwnerID) REFERENCES OWNER(OwnerID)
);

CREATE TABLE BREED (
    PetID INTEGER NOT NULL
    ,BreedType TEXT NOT NULL
    ,PRIMARY KEY (PetID, BreedType)
    ,FOREIGN KEY (PetID) REFERENCES PET(PetID) ON DELETE CASCADE
);

CREATE TABLE BEHAVIOR_TAG (
    TagID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    ,Behavior TEXT NOT NULL
);

CREATE TABLE PET_TAG (
    PetID INTEGER NOT NULL 
    ,TagID INTEGER NOT NULL
    ,PRIMARY KEY (PetID, TagID)
    ,FOREIGN KEY (PetID) REFERENCES PET(PetID) ON DELETE CASCADE
    ,FOREIGN KEY (TagID) REFERENCES BEHAVIOR_TAG(TagID) ON DELETE CASCADE
);

CREATE TABLE PLAYROOM (
    RoomID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    ,RoomName TEXT NOT NULL
    ,MaxCapacity INTEGER NOT NULL CHECK (MaxCapacity > 0)
);

CREATE TABLE VISIT (
    VisitID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    ,PetID INTEGER NOT NULL
    ,RoomID INTEGER NOT NULL
    ,VisitType TEXT CHECK(VisitType IN ('Reservation', 'Walk-in'))
    ,VisitDate TEXT
    ,StartTime TEXT
    ,EndTime TEXT
    ,Notes TEXT
    ,FOREIGN KEY (PetID) REFERENCES PET(PetID) ON DELETE CASCADE
    ,FOREIGN KEY (RoomID) REFERENCES PLAYROOM(RoomID)
);

CREATE TABLE BOOKING (
    BookingID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
    ,PetID INTEGER NOT NULL
    ,RoomID INTEGER NOT NULL
    ,StartDate TEXT NOT NULL
    ,StartTime TEXT NOT NULL
    ,Status TEXT DEFAULT 'Confirmed' NOT NULL
    ,FOREIGN KEY (PetID) REFERENCES PET(PetID) ON DELETE CASCADE
    ,FOREIGN KEY (RoomID) REFERENCES PLAYROOM(RoomID)
);



